# Discussion

Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante (Table \@ref(tab:functions)).
```{r tab}

my_tbl <- tibble::tribble(
  ~Época, ~Sitio, ~Zona, ~Pozo,  ~WT,  ~pH, ~Temp,    ~CE,
     "S",      1,     0,     7, 57.5, 5.63,     8,  218.6,
     "S",      1,     0,     8, 25.5, 5.67,   8.6,  389.9,
     "S",      1,     0,     9,   29, 5.45,   9.5, 1036.2,
     "S",      1,     0,     3, 39.5, 5.69,   7.6,    362,
     "S",      1,     0,     1,   53, 5.99,   8.1,  365.6,
     "S",      1,   0.5,     3, 26.5, 4.52,     8,  945.5,
     "S",      1,   0.5,     4,   40, 5.02,   9.3,  658.9,
     "S",      1,   0.5,    11,   25, 5.65,   7.9,  506.1,
     "S",      1,   0.5,    16,   30, 5.49,   8.1,  613.3
  )


knitr::kable(
  my_tbl,
  booktabs = TRUE,
  caption = "Pozos y variables y ambientales."
  )




```


Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. 

Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue. Proin sodales libero eget ante. Nulla quam. Aenean laoreet. Vestibulum nisi lectus, commodo ac, facilisis ac, ultricies eu, pede. Ut orci risus, accumsan porttitor, cursus quis, aliquet eget, justo. Sed pretium blandit orci. Ut eu diam at pede suscipit sodales. Aenean lectus elit, fermentum non, convallis id, sagittis at, neque. Nullam mauris orci, aliquet et, iaculis et, viverra vitae, ligula. Nulla ut felis in purus aliquam imperdiet.